# Generated by Django 4.0.4 on 2022-05-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('about_you', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('career', models.CharField(max_length=200)),
                ('job1start', models.DateField(default=' ')),
                ('job1end', models.DateField(default=' ')),
                ('job1details', models.TextField(default=' ', max_length=200)),
                ('job2start', models.DateField(default=' ')),
                ('job2end', models.DateField(default=' ')),
                ('job2details', models.TextField(default=' ', max_length=200)),
                ('job3start', models.DateField(default=' ')),
                ('job3end', models.DateField(default=' ')),
                ('job3details', models.TextField(default=' ')),
                ('references', models.TextField(max_length=1000)),
            ],
        ),
    ]
